unit Windows;

interface

const
    VK_LBUTTON = $01;
    VK_RBUTTON = $02;
    VK_CANCEL = $03;
    VK_MBUTTON = $04;
    VK_XBUTTON1 = $05;
    VK_XBUTTON2 = $06;
    VK_BACK = $08;
    VK_TAB = $09;
    VK_CLEAR = $0C;
    VK_RETURN = $0D;
    VK_SHIFT = $10;
    VK_CONTROL = $11;
    VK_MENU = $12;
    VK_PAUSE = $13;
    VK_CAPITAL = $14;
    VK_KANA = $15;
    VK_HANGUEL = $15;
    VK_HANGUL = $15;
    VK_JUNJA = $17;
    VK_FINAL = $18;
    VK_HANJA = $19;
    VK_KANJI = $19;
    VK_ESCAPE = $1B;
    VK_CONVERT = $1C;
    VK_NONCONVERT = $1D;
    VK_ACCEPT = $1E;
    VK_MODECHANGE = $1F;
    VK_SPACE = $20;
    VK_PRIOR = $21;
    VK_NEXT = $22;
    VK_END = $23;
    VK_HOME = $24;
    VK_LEFT = $25;
    VK_UP = $26;
    VK_RIGHT = $27;
    VK_DOWN = $28;
    VK_SELECT = $29;
    VK_PRINT = $2A;
    VK_EXECUTE = $2B;
    VK_SNAPSHOT = $2C;
    VK_INSERT = $2D;
    VK_DELETE = $2E;
    VK_HELP = $2F;
    VK_LWIN = $5B;
    VK_RWIN = $5C;
    VK_APPS = $5D;
    VK_SLEEP = $5F;
    VK_NUMPAD0 = $60;
    VK_NUMPAD1 = $61;
    VK_NUMPAD2 = $62;
    VK_NUMPAD3 = $63;
    VK_NUMPAD4 = $64;
    VK_NUMPAD5 = $65;
    VK_NUMPAD6 = $66;
    VK_NUMPAD7 = $67;
    VK_NUMPAD8 = $68;
    VK_NUMPAD9 = $69;
    VK_MULTIPLY = $6A;
    VK_ADD = $6B;
    VK_SEPARATOR = $6C;
    VK_SUBTRACT = $6D;
    VK_DECIMAL = $6E;
    VK_DIVIDE = $6F;
    VK_F1 = $70;
    VK_F2 = $71;
    VK_F3 = $72;
    VK_F4 = $73;
    VK_F5 = $74;
    VK_F6 = $75;
    VK_F7 = $76;
    VK_F8 = $77;
    VK_F9 = $78;
    VK_F10 = $79;
    VK_F11 = $7A;
    VK_F12 = $7B;
    VK_F13 = $7C;
    VK_F14 = $7D;
    VK_F15 = $7E;
    VK_F16 = $7F;
    VK_F17 = $80;
    VK_F18 = $81;
    VK_F19 = $82;
    VK_F20 = $83;
    VK_F21 = $84;
    VK_F22 = $85;
    VK_F23 = $86;
    VK_F24 = $87;
    VK_NUMLOCK = $90;
    VK_SCROLL = $91;
    VK_LSHIFT = $A0;
    VK_RSHIFT = $A1;
    VK_LCONTROL = $A2;
    VK_RCONTROL = $A3;
    VK_LMENU = $A4;
    VK_RMENU = $A5;
    VK_BROWSER_BACK = $A6;
    VK_BROWSER_FORWARD = $A7;
    VK_BROWSER_REFRESH = $A8;
    VK_BROWSER_STOP = $A9;
    VK_BROWSER_SEARCH = $AA;
    VK_BROWSER_FAVORITES = $AB;
    VK_BROWSER_HOME = $AC;
    VK_VOLUME_MUTE = $AD;
    VK_VOLUME_DOWN = $AE;
    VK_VOLUME_UP = $AF;
    VK_MEDIA_NEXT_TRACK = $B0;
    VK_MEDIA_PREV_TRACK = $B1;
    VK_MEDIA_STOP = $B2;
    VK_MEDIA_PLAY_PAUSE = $B3;
    VK_LAUNCH_MAIL = $B4;
    VK_LAUNCH_MEDIA_SELECT = $B5;
    VK_LAUNCH_APP1 = $B6;
    VK_LAUNCH_APP2 = $B7;
    VK_OEM_1 = $BA;
    VK_OEM_PLUS = $BB;
    VK_OEM_COMMA = $BC;
    VK_OEM_MINUS = $BD;
    VK_OEM_PERIOD = $BE;
    VK_OEM_2 = $BF;
    VK_OEM_3 = $C0;
    VK_OEM_4 = $DB;
    VK_OEM_5 = $DC;
    VK_OEM_6 = $DD;
    VK_OEM_7 = $DE;
    VK_OEM_8 = $DF;
    VK_OEM_102 = $E2;
    VK_PROCESSKEY = $E5;
    VK_PACKET = $E7;
    VK_ATTN = $F6;
    VK_CRSEL = $F7;
    VK_EXSEL = $F8;
    VK_EREOF = $F9;
    VK_PLAY = $FA;
    VK_ZOOM = $FB;
    VK_NONAME = $FC;
    VK_PA1 = $FD;
    VK_OEM_CLEAR = $FE;

    SW_HIDE = 0;
    SW_MAXIMIZE = 3;
    SW_MINIMIZE = 6;
    SW_RESTORE = 9;
    SW_SHOW = 5;
    SW_SHOWDEFAULT = 10;
    SW_SHOWMAXIMIZED = 3;
    SW_SHOWMINIMIZED = 2;
    SW_SHOWMINNOACTIVE = 7;
    SW_SHOWNA = 8;
    SW_SHOWNOACTIVATE = 4;
    SW_SHOWNORMAL = 1;

type
    HINSTANCE = longint;
    HWND = longint;

function ShellExecute(wnd: HWND; lpOperation: String; lpFile: String; lpParameters: Longint; lpDirectory: String; nShowCmd: Integer): HINSTANCE;
function MessageDlg(const Msg: string; DlgType: TMsgDlgType; Buttons: TMsgDlgButtons; HelpCtx: Longint): Integer;

implementation

function ShellExecute(wnd: HWND; lpOperation: String; lpFile: String; lpParameters: Longint; lpDirectory: String; nShowCmd: Integer): HINSTANCE;
begin
    ShellExecute := 0;
end;

function MessageDlg(const Msg: string; DlgType: TMsgDlgType; Buttons: TMsgDlgButtons; HelpCtx: Longint): Integer;
begin
    MessageDlg := 0;
end;

end.
